export const CART = {
    FETCH_START: 'CART.FETCH_START',
    FETCH_DONE: 'CART.FETCH_DONE',
    FETCH_FAIL: 'CART.FETCH_FAIL',
    ADD_ITEM: 'CART.ADD_ITEM',
    TOGGLE: 'CART.TOGGLE',
    MODAL_HIDE: 'CART.MODAL_HIDE',
    SENDING: 'CART.SENDING',
    SENT: 'CART.SENT',
    CLEAR_SENT_MESSAGE: 'CART.CLEAR_SENT_MESSAGE'
};

export const ITEM_DETAILS = {
    OPEN: 'ITEM_DETAILS.OPEN',
    CHOOSE_OPTION: 'ITEM_DETAILS.CHOOSE_OPTION',
    CLOSE: 'ITEM_DETAILS.CLOSE'
};
