export const CART = {
    FETCH_START: 'CART.FETCH_START',
    FETCH_DONE: 'CART.FETCH_DONE',
    FETCH_FAIL: 'CART.FETCH_FAIL',
    ADD_ITEM: 'CART.ADD_ITEM',
    TOGGLE: 'CART.TOGGLE',
    SENDING: 'CART.SENDING',
    SENT: 'CART.SENT',
    CLEAR_SENT_MESSAGE: 'CART.CLEAR_SENT_MESSAGE'
};
